### ISSUE TITLE
How about http dialet？

### ISSUE THREAD

**Issue by zhjygit** [ysmei97/MPD#1]
Hi sir，this project is cool
If i want to do mtd on http dialet, how i will recode eth client、server、dialets.py and thread_function.py，do you have some templates for copy？

**Comment by ysmei97** [comment]
Thanks for your interest. The dialects were included in dialects.py. Unfortunately, I don't have the ready-made version of MTD for the HTTP protocol. However, if you are interested, you may try the same design for application-level HTTP packets like this one for FTP. You will need the HTTP client and server, and you also need to adapt dialects in dialects.py for your purpose.
