### ISSUE TITLE
how do i apply dialets mtd to a router device?

### ISSUE THREAD

**Issue by zhjygit** [ysmei97/MPD#2]
If i have a tplink route with lighttpd service running, how  will I apply dialets mtd to the lighttpd server.
Imaging that, my client is just a web browser, how can I run mpd project on it?
Is there some advice or papers about http-mtd-dialets? Maybe It is userful.

**Comment by ysmei97** [comment]
In this work, we mainly use the lab protocol simulation to demonstrate the effectiveness of our approach. For real-world devices, you may need to consider the specific requirements to adopt this method, e.g., the permit to make certain modifications. To utilize this framework, you can start with a simulation of the HTTP client-server system. If you're already familiar with the protocol, you may investigate real-world devices/applications more for further implementation.
